### ISSUE TITLE
BOM for SMD Version

### ISSUE THREAD

**Issue by homekiciarz** [der-pw/USB-Joyadapter_SMD#1]
Hello. I try to make this project.
I Can't find anywhere BOM for this project so i decide to try made one myself.
Can You confirm or correct it and add to Your project for other people.

U1 ATtiny4313-SU/ATtiny2313-SU
D1,D2 Zener Diode (I don't know what parameters they are have)
F1 0805 Fuse
R1,R2 0805 Resistor 68R
R3 0805 Resistor 10k
R4 0805 Resistor 1,5k
C2 3216 Tantal Capacitor 10uF
C1 0805 Capacitor 100nF
C3,C4 0805 Capacitor 22pF
Y1 Crystal 12MHz SMD

Please insert correct values for D1 and  D2

**Comment by der-pw** [comment]
Hi, 
just created the parts list at Reichelt.
I didn't do a BOM yet. I probably forgot to add the zener diodes, sorry. It is a "SMD ZF 3.6 Zener diode, 3.6 V, 0.5 W, SOD80". 
I have now also added it to my Reichelt list. Incidentally, I had not solder the fuse, but rather short-circuited the pads.
Otherwise, your list looks fine. 
You can leave out C2 or solder a big 10u ceramic capacitor. I made the pad just to be safe, in critical cases. I try to leave out tantalum as much as possible. 
The Attiny runs fine, just with the 100nF.
